### ISSUE TITLE
Create component for header menu

### ISSUE THREAD

**Issue by 10-seconds** [10secondsofcode/blog#7]
# Create component for header menu

**Comment by randomvi** [comment]
Hi what content should be put on this header menu component?

**Comment by elangovanshanthi** [comment]
@randomvi thanks, menu should be as home, javascript, reactjs, events,.

**Comment by lnormanha** [comment]
I submitted a PR with the component, let me know if it meet your needs :)

**Comment by elangovanshanthi** [comment]
@lnormanha thanks for your help
